### ISSUE TITLE
Where is the latest code and build instructions

### ISSUE THREAD

**Issue by Giszmo** [TP-Lab/tp-android#15]
In the description of [the app](https://play.google.com/store/apps/details?id=vip.mytokenpocket) I read that it's "open source" but this repo here is stale and uses a different `applicationId`. It also lists different features.

I'm reviewing wallets and would love to see the latest code and ideally build instructions to reproduce the binaries from the Play Store but at least no obfuscation (ProGuard minification).

[Here you will find my full review later today](https://walletscrutiny.com/android/vip.mytokenpocket/).

**Comment by chendatony31** [comment]
Hi, Giszmo, thanks for reaching out to us. We do not open-sourced the latest code of our wallet product. Just an early version of it.

**Comment by Giszmo** [comment]
So my verdict "closed source" is correct. Thanks. Let me know if you reconsider. Also please don't make such misleading claims on your website. :(
