### ISSUE TITLE
Add support for `eth_signTypedData_v4`

### ISSUE THREAD

**Issue by alfetopito** [TP-Lab/tp-android#16]
Any thoughts on adding support for `eth_signTypedData_v4`?

TokenPocket works perfectly with our app using the dApp browser, but through WalletConnect it fails what a message in the phone app: `Not currently supported`

Our app uses offline signatures for placing orders.

To reproduce the issue:
1. Head to https://cowswap.exchange
2. Connect your wallet using WalletConnect
3. Pick a token pair and fill in an amount
4. Enable the sell token
5. Try to perform a Swap

You can try on Rinkeby and save yourself some gas :)

Platform: Android
Version: 1.2.6

**Comment by tararara1111** [comment]
> Any thoughts on adding support for `eth_signTypedData_v4`?
> 
> TokenPocket works perfectly with our app using the dApp browser, but through WalletConnect it fails what a message in the phone app: `Not currently supported`
> 
> Our app uses offline signatures for placing orders.
> 
> To reproduce the issue:
> 
> 1. Head to https://cowswap.exchange
> 2. Connect your wallet using WalletConnect
> 3. Pick a token pair and fill in an amount
> 4. Enable the sell token
> 5. Try to perform a Swap
> 
> You can try on Rinkeby and save yourself some gas :)
> 
> Platform: Android
> Version: 1.2.6

**Comment by chendatony31** [comment]
Will support in next release.

**Comment by chendatony31** [comment]
@alfetopito  WalletConnet option seems been removed from cowswap.exchange. Any other site we can test?

**Comment by alfetopito** [comment]
@chendatony31 oh, sorry about that.

~We have WalletConnect enabled on this dev version https://pr597--gpswapui.review.gnosisdev.com/~

See https://github.com/TP-Lab/tp-android/issues/16#issuecomment-848250217

**Comment by anxolin** [comment]
> Will support in next release

Great news! 🎉 
How often do you release?  Is there an ETA for it?

**Comment by chendatony31** [comment]
Early June I think @anxolin

**Comment by alfetopito** [comment]
Update, the link above will no longer work.
I've created a new on that has TokenPocket enabled via WalletConnect: https://pr674--gpswapui.review.gnosisdev.com/#/swap

**Comment by chendatony31** [comment]
Hi, The new version with `eth_signTypedData` supported has been released. Please try to update @alfetopito   @anxolin   @tararara1111.

**Comment by alfetopito** [comment]
It's working perfectly, thanks a lot!

Just tested on Android version 1.2.8
