### ISSUE TITLE
Publish code for vip.mytokenpocket app on Google Play or remove "open-sourced" claims in description

### ISSUE THREAD

**Issue by emanuelb** [TP-Lab/tp-android#22]
From https://play.google.com/store/apps/details?id=vip.mytokenpocket
> 1. An **open-sourced** decentralized wallet, keep your cryptocurrencies safe
• It is an **open-sourced** and non-custodial decentralized wallet that stores your private keys on users' device

The description claims this app is open-source but it's incorrect as the source-code for it is not published in this repo, the app on google-play last updated in "September 22, 2021" with version "1.3.3" while latest commit in this repo is from " Jan 5, 2019" and with different appid `com.tokenbank` and version `1.0.0`
https://github.com/TP-Lab/tp-android/blob/master/app/build.gradle#L7

Please publish the source code for the app on google-play in this repo, if code isn't published please remove the claims that app is "open-sourced".

also source-code was not found in other repos in this org, like:
https://github.com/TP-Lab/tp-wallet-android-deprecated
https://github.com/TP-Lab/tp-wallet-native-android

edit: source code was also not found in org https://github.com/tokenbankteam

**Comment by imxieke** [comment]
hey man , I agree with you. and imtoken  are the same as this
shan le kaiyuan zhe ge zi ba laotie 
wo hao gan ga  dou bu hao yi si le

**Comment by mrkomarov** [comment]
will @TP-Lab give any update on this?

**Comment by emanuelb** [comment]
Why this issue was closed? @heipacker will the source code of the app be published on github or the claim of it's being open-source will be removed from description on Google Play?

There is another open issue regarding the missing sources for the latest release in #18
