### ISSUE TITLE
交易记录精度不显示问题

### ISSUE THREAD

**Issue by jklongtest10** [TP-Lab/tp-android#27]
bsc链上的 token 0xf8169dDee9bC743ad953f194136D0CE3B9c728DD 
再 bscscan上显示正常的，但是在tp钱包
添加代币正常
![image](https://user-images.githubusercontent.com/71110449/158043196-665a0c31-b226-43bd-b981-ad592db5f811.png)

代币的交易记录 显示不正常
![image](https://user-images.githubusercontent.com/71110449/158043211-46ac5e94-8280-4e71-81fe-37e079cdfc30.png)
交易记录 没有处理精度

**Comment by heipacker** [comment]
你版本号是多少， 是最新的吗

**Comment by jklongtest10** [comment]
android 版本1.3.4

**Comment by jklongtest10** [comment]
刚才升级了最新版本1.4.1 发现 
![image](https://user-images.githubusercontent.com/71110449/158047607-40da0876-2cce-4681-94a3-3a04783146a5.png)
资产余额还是 没有计算精度 
交易列表好像好了

**Comment by Developmc** [comment]
试下删除代币，重新添加

**Comment by jklongtest10** [comment]
> 试下删除代币，重新添加

删除之后 再增加，交易记录中处理了精度 单数
