### ISSUE TITLE
使用walletconnet 连接，chainId只返回1

### ISSUE THREAD

**Issue by zfamz** [TP-Lab/tp-android#28]
环境： 
TokenPocket:  1.4.3
@walletconnect/web3-provider: 1.7.3

安卓出现这个问题， IOS正常

**Comment by Developmc** [comment]
目前Android返回的chainId是建立walletConnect时，DApp传过来的chainId。如果chainId不为空，则使用DApp传过来得chainId；如果为空，则使用钱包网络对应的chainId。

1.在这个问题里，请检查你们传过来的chainId是否是1，如果希望返回的chainId是跟随当前钱包的，请将传过来的chainId值设置为空。

2.我们将在新版本(Android V1.4.4)优化这个逻辑：返回的chainId始终是当前钱包网络的chainId

**Comment by zfamz** [comment]
> 目前Android返回的chainId是建立walletConnect时，DApp传过来的chainId。如果chainId不为空，则使用DApp传过来得chainId；如果为空，则使用钱包网络对应的chainId。
> 
> 1.在这个问题里，请检查你们传过来的chainId是否是1，如果希望返回的chainId是跟随当前钱包的，请将传过来的chainId值设置为空。
> 
> 2.我们将在新版本(Android V1.4.4)优化这个逻辑：返回的chainId始终是当前钱包网络的chainId

🍁  感谢答复。 使用@walletconnect/web3-provider库的时候，不传chianId 它会默认赋值1。 然后我去node_modules改源码,去掉这个参数，逻辑就是ok的。
