### ISSUE TITLE
[tp 1.5.4] nft详情页面无法展示不包含完整http 链接 的ipfs图片

### ISSUE THREAD

**Issue by gpBlockchain** [TP-Lab/tp-android#39]
版本: tp 1.5.4
合约地址: 0xDf55191D6cF0CE207D9b70dD3bB859744fd50B8C
链:币安链
能够在nft scan上展示，但是无法在tp钱包里展示
https://bnb.nftscan.com/0xDf55191D6cF0CE207D9b70dD3bB859744fd50B8C
### nftscan
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/32102187/181051696-81d55f2f-420d-4e47-9a69-1c4249db776c.png">
### tp钱包

![image](https://user-images.githubusercontent.com/32102187/181051315-56d769de-3066-442e-815a-40140b356fcf.png)

调用token 1d的url 为:ipfs://ipfs/QmdT7wd5Qfqb3gubnmyFqgZyXzSrexQfHqra9AaJvzHKhA
<img width="386" alt="image" src="https://user-images.githubusercontent.com/32102187/181052355-6f8eb574-1122-417d-8db0-a2b920a1fa04.png">

通过ipfs ：https://ipfs.io/ipfs/QmdT7wd5Qfqb3gubnmyFqgZyXzSrexQfHqra9AaJvzHKhA    查询：{"image":"ipfs://ipfs/QmQpLcz6GAe5oFifLuCBoVhoSJMyiDB91SZ1ZCpEUWNLxU","animation_url":"","name":"皮箱","description":"12323","attributes":[]}

对应的图片url链接为: ipfs://ipfs/QmQpLcz6GAe5oFifLuCBoVhoSJMyiDB91SZ1ZCpEUWNLxU
查询图片:https://ipfs.io/ipfs/QmQpLcz6GAe5oFifLuCBoVhoSJMyiDB91SZ1ZCpEUWNLxU

预期: 希望tp钱包能够自动补全ipfs的url，不知道有没有相应的计划？

**Comment by heipacker** [comment]
这个应该已经修复了
